/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-0iA3kxQTUJ3DB4gu8hMFQ-MpOUAsBNjVkD-W92sECcwEqVkBBxQ9-0hgA13Nq6zn65TZI-taPIW93hLu9ndC6-7xV-gybtoN-ov7AA29NkKqIglP4D6EEUNs",
  "tt": "tt-1-SvHUaPFDJfJOIsLmt5F38lef8odbUzD-VSQfWOE7Fls=",
  "version": "2020-11-20"
}

export default ebconfig;